### ISSUE TITLE
DFAnalyzer's column editor (many column mode)

### ISSUE THREAD

**Issue by jonathanrocher** [KBIbiopharma/pybleau#84]
`DFAnalyzer`'s column editor: in the large column number mode, the column editor is a pop up dialog. If you open it, close it and try to reopen it again, it fails to reopen with the following traceback:

```
2020-08-04 16:21:45 ERROR    [traits:221] Exception occurred in traits notification handler for object: <pybleau.app.ui.dataframe_analyzer_model_view.DataFrameAnalyzerView object at 0x7f84bd9852b0>, trait: open_column_controls, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/Users/jrocher/.edm/envs/particle_data_viewer-develop-py36/lib/python3.6/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler(*args)
  File "/Users/jrocher/Projects/pybleau/pybleau/app/ui/dataframe_analyzer_model_view.py", line 488, in _open_column_controls_fired
    self._control_popup.control._mw.activateWindow()
AttributeError: 'NoneType' object has no attribute '_mw'
```

**Comment by chamshop** [comment]
@jonathanrocher Is it possible to add some steps to replicate this issue?
